import React from 'react';
import './MarqueeNotice.css'; // Import your CSS file for styling

const MarqueeNotice = ({text}) => {

  return (
<>
<div class="logos">
      <div className="logos-slide">
      ADMISSIONS FOR THE UPCOMING ACADEMIC YEAR ARE NOW OPEN ! APPL NOW TO JOIN OUR VIBRANT COMMUNITY. | THE ADMISSION PROCESS HAS BEEN STARTED AND WILL BE AVAILABLE TILL 10/03/2024 | THE START DATE FOR THE UPCOMING SCHOOL SESSION IS 01/07/2024. WE CAN'T WAIT TO WELCOME OUR STUDENTS BACK FOR ANOTHER ENRICHING YEAR OF LEARNING AND GROWTH. | OUR SCHOOL HAS IMPLEMENTED A NEW ONLINE ADMISSION PROCESS FOR ADDED CONVENIENCE AND ACCESSIBILITY. VISIT OUR WEBSITE FOR DETAILS ON HOW TO APPLY. |  KEEP UP-TO-DATE WITH THE LATEST SCHOOL NEWS AND ANNOUNCEMENTS BY SUBSCRIBING TO OUR NEWSLETTER. DON'T MISS OUT ON IMPORTANT UPDATES REGARDING EVENTS, ADMISSIONS, AND MORE! |
      </div>

      <div className="logos-slide">
      ADMISSIONS FOR THE UPCOMING ACADEMIC YEAR ARE NOW OPEN ! APPL NOW TO JOIN OUR VIBRANT COMMUNITY. | THE ADMISSION PROCESS HAS BEEN STARTED AND WILL BE AVAILABLE TILL 10/03/2024 | THE START DATE FOR THE UPCOMING SCHOOL SESSION IS 01/07/2024. WE CAN'T WAIT TO WELCOME OUR STUDENTS BACK FOR ANOTHER ENRICHING YEAR OF LEARNING AND GROWTH. | OUR SCHOOL HAS IMPLEMENTED A NEW ONLINE ADMISSION PROCESS FOR ADDED CONVENIENCE AND ACCESSIBILITY. VISIT OUR WEBSITE FOR DETAILS ON HOW TO APPLY. | KEEP UP-TO-DATE WITH THE LATEST SCHOOL NEWS AND ANNOUNCEMENTS BY SUBSCRIBING TO OUR NEWSLETTER. DON'T MISS OUT ON IMPORTANT UPDATES REGARDING EVENTS, ADMISSIONS, AND MORE! |
  
      </div>
      </div>
</>

  );
};

export default MarqueeNotice;
